@API_HostAddress = http://localhost:8080

GET {{API_HostAddress}}/api/items
Accept: application/json

###

GET {{API_HostAddress}}/api/items/9
Accept: application/json

###
POST {{API_HostAddress}}/api/auth/register 
Content-Type: application/json

{
    "Username": "lukasz",
    "Password": "lukasz"
}
###
POST {{API_HostAddress}}/api/auth/login 
Content-Type: application/json

{
    "Username": "lukasz5",
    "Password": "lukasz"
}
###
POST {{API_HostAddress}}/api/items
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiNjRlMmNjYy0wNGZkLTRlOTYtYjkwNy04OTQwYWE5NDhiNjQiLCJqdGkiOiI3M2E2MGQzNS03ZWQwLTQ0MzktYjVhYi05OTBmM2M1NWU5NDgiLCJleHAiOjE3MTkzMTMyMDMsImlzcyI6InByb2plY3QubmV0IiwiYXVkIjoicHJvamVjdC5uZXQifQ.W8fXmfh5ochGtxl6D3EioU2GN_XASm_WgNnqOvTVWZk
Content-Type: application/json

{
    "Title": "Ksiazka",
    "Description": "Fajna",
    "price": 19.99
}
###

PUT {{API_HostAddress}}/api/items/9
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiNjRlMmNjYy0wNGZkLTRlOTYtYjkwNy04OTQwYWE5NDhiNjQiLCJqdGkiOiI3M2E2MGQzNS03ZWQwLTQ0MzktYjVhYi05OTBmM2M1NWU5NDgiLCJleHAiOjE3MTkzMTMyMDMsImlzcyI6InByb2plY3QubmV0IiwiYXVkIjoicHJvamVjdC5uZXQifQ.W8fXmfh5ochGtxl6D3EioU2GN_XASm_WgNnqOvTVWZk
Content-Type: application/json

{
    "Title": "Harry Potter",
    "Description": "I zakon feniksa",
    "price": 9.99,
    "isAvailable": false
}

###

GET {{API_HostAddress}}/api/items/myitems
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiNjRlMmNjYy0wNGZkLTRlOTYtYjkwNy04OTQwYWE5NDhiNjQiLCJqdGkiOiI3M2E2MGQzNS03ZWQwLTQ0MzktYjVhYi05OTBmM2M1NWU5NDgiLCJleHAiOjE3MTkzMTMyMDMsImlzcyI6InByb2plY3QubmV0IiwiYXVkIjoicHJvamVjdC5uZXQifQ.W8fXmfh5ochGtxl6D3EioU2GN_XASm_WgNnqOvTVWZk
Accept: application/json
